# Generated by Django 4.2.3 on 2023-07-23 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='orgcustomer',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_customer', to='organisation.organisation'),
        ),
    ]
